### PR TITLE
controlsSlider

### PR DESCRIPTION
**Pull request by aaronli03**
## What
- custom slider for controls

## Why
- to match current designs

## Impact
- Will customer experience be significantly altered? No
- Does the code change cover more than one task? No

## Testing
- tested locally by running `npm run dev`

### CODE REVIEW

**Comment by byjackli** [comment]
The controls are small. Have you conducted usability testing on small mobile phones? Feature needs more work.

**Comment by byjackli** [comment]
Since this component is going to be on a clear background, you should emulate that on the container so its closer to a real-world environment. As of right now, it will forsure fail accessibility.

**Comment by aaronli03** [comment]
> The controls are small. Have you conducted usability testing on small mobile phones? Feature needs more work.

Haven't tested for mobile yet

**Comment by byjackli** [comment]
> 

okay let me know when you finish

**Comment by aaronli03** [comment]
Updates:
- Controls are larger.
- Slider functionality works with touch.

**Review by byjackli — APPROVED** [review]
Keyboard accessibility is lacking hard. Add a backlog task to the tracker and post a link here to that task.

**Comment by aaronli03** [comment]
keyboard accessibility needs to be added

**Comment by aaronli03** [comment]
try to implement gliding thumb

**Pull request merged**
